PREFIX plat: <http://mobi.com/ontologies/platform/config#>

SELECT
    ?id
    (GROUP_CONCAT(DISTINCT ?resource ; separator = ",") AS ?resources)
WHERE {
    ?id a plat:ApplicationState ;
        plat:forUser ?userId ;
        plat:stateResource ?resource .

	FILTER EXISTS { ?id plat:application ?application } .
} GROUP BY ?id