prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?parent ?child
where {
    ?parent rdf:type/rdfs:subClassOf* skos:Concept .
    optional {
        ?child skos:broaderTransitive ?parent ;
               rdf:type/rdfs:subClassOf* skos:Concept .
    }
    optional {
        ?child skos:broader ?parent ;
               rdf:type/rdfs:subClassOf* skos:Concept .
    }
    optional {
        ?child skos:broadMatch ?parent ;
               rdf:type/rdfs:subClassOf* skos:Concept .
    }
    optional {
        ?child ^skos:narrowerTransitive ?parent ;
               rdf:type/rdfs:subClassOf* skos:Concept .
    }
    optional {
        ?child ^skos:narrower ?parent ;
               rdf:type/rdfs:subClassOf* skos:Concept .
    }
    optional {
        ?child ^skos:narrowMatch ?parent ;
               rdf:type/rdfs:subClassOf* skos:Concept .
    }
}