DELETE {
    GRAPH ?dataset {
        ?dataset <http://mobi.com/ontologies/graph#lastAccessed> ?lastAccessed
    }
}
INSERT {
    GRAPH ?dataset {
        ?dataset <http://mobi.com/ontologies/graph#lastAccessed> ?now
    }
}
WHERE {
    GRAPH ?dataset {
        ?dataset <http://mobi.com/ontologies/graph#lastAccessed> ?lastAccessed
    }
}