PREFIX mcat: <http://matonto.org/ontologies/catalog#>
PREFIX ontedit: <http://matonto.org/ontologies/ontology-editor#>

SELECT ?record
WHERE {
	?branch a mcat:Branch .

    ?record a ontedit:OntologyRecord ;
        mcat:branch ?branch ;
        mcat:masterBranch ?branch .
}