/*-
 * #%L
 * com.mobi.web
 * $Id:$
 * $HeadURL:$
 * %%
 * Copyright (C) 2016 - 2022 iNovex Information Systems, Inc.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */
import './visualizationTab.component.scss';
const template = require('./visualizationTab.component.html');

/**
 * @ngdoc component
 * @name ontology-editor.component:visualizationTab
 *
 * @description
 * `visualizationTab` is a component that creates a page containing an interactive visualization of ontologies.
 * {@link shared.service:ontologyStateService selected ontology}.
 * This component renders a force-directed graph using d3-force layout representing the selected ontology.
 * The graph is generated by the data retrived from ontologyStateService and ontologyManagerService. 
 * The vizualiation has a limit of 500
 * InProgressCommits are not displayed.
 * @todo
 * upgrade to angular component.
 */
const visualizationTabComponent = {
    template,
    bindings: {},
    controllerAs: 'dvm',
    controller: visualizationTabComponentCtrl
};

visualizationTabComponentCtrl.$inject = ['ontologyStateService'];

function visualizationTabComponentCtrl(ontologyStateService) {
    let dvm = this;
    dvm.os = ontologyStateService;
}

export default visualizationTabComponent;
