PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?class ?prop WHERE {
    VALUES ?type { owl:DatatypeProperty owl:ObjectProperty }
    ?class a owl:Class .
    ?prop a ?type ;
        rdfs:domain ?class .
}
