PREFIX : <urn:ex:>

CONSTRUCT {
    ?entity ?p ?o .
    ?attachedObj ?p2 ?o2 .
} WHERE {
    ?entity (:|!:)* ?attachedObj ;
        ?p ?o .

    OPTIONAL {
        ?attachedObj ?p2 ?o2 .
        FILTER(isBlank(?attachedObj))
    }
}
