PREFIX : <urn:ex:>

CONSTRUCT {
    %ENTITY% ?p ?o .
    ?attachedObj ?p2 ?o2 .
} WHERE {
    {
        SELECT DISTINCT ?attachedObj WHERE {
            %ENTITY% (:|!:)* ?attachedObj .

            FILTER NOT EXISTS {
                {
                    SELECT DISTINCT ?iris WHERE {
                        %ENTITY% (:|!:)* ?iris .
                        FILTER(isIRI(?iris))
                        FILTER(?iris != %ENTITY%)
                    }
                }
                ?iris (:|!:)* ?attachedObj .
            }
        }
    }

    %ENTITY% ?p ?o .

    OPTIONAL {
        ?attachedObj ?p2 ?o2 .
        FILTER(isBlank(?attachedObj))
    }
}
