
language: java

# Cobertura is not supported in JDK11 so you must downgrade the JDK that Travis uses if you want to use Cobertura with Travis.
# https://github.com/cobertura/cobertura/issues/381
jdk:
  - openjdk8

# sudo: false # faster builds

# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step

services:
  - docker

cache:
  directories:
  - $HOME/.m2

install: true

before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 10 # for Node v5
  - node --version


script: 
    - travis_wait 60 mvn clean install -DskipFunctional=false -DskipITs=false -l temp.build.log ; grep -B 1 -A 500 Reactor\ Summary temp.build.log; rm temp.build.log


