PREFIX mcat: <http://mobi.com/ontologies/catalog#>

ASK {
    ?mergeCommit mcat:mergeDisplayRevision ?mergeRev .

    ?mergeRev mcat:deletions ?mergeRevDels .

    GRAPH ?mergeRevDels {
        ?s ?p ?o .
    }
}