prefix rdf: <http://www.w3.org/1999/22-rdf-schema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?prop ?value
WHERE {
        ?s a owl:AnnotationProperty .

        <%1$s> ?prop ?value .
}
