prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select distinct ?parent ?individual
where {
    values ?type {owl:Class rdfs:Class}
    ?parent rdf:type/rdfs:subClassOf* ?type .
    optional {
        ?child rdfs:subClassOf ?parent ;
               rdf:type ?type .
    }
    {
        ?individual rdf:type ?parent .
        filter ( ?parent != owl:NamedIndividual )
        filter ( !isBlank ( ?parent ) )
        filter ( !isBlank ( ?individual ) )
    }
    UNION
    {
        ?individual rdf:type/rdfs:subClassOf* skos:Concept ;
                    rdf:type ?parent .
        filter ( ?parent != owl:NamedIndividual )
        filter ( !isBlank ( ?parent ) )
        filter ( !isBlank ( ?individual ) )
    }
    UNION
    {
        ?individual rdf:type/rdfs:subClassOf* skos:ConceptScheme ;
                    rdf:type ?parent .
        filter ( ?parent != owl:NamedIndividual )
        filter ( !isBlank ( ?parent ) )
        filter ( !isBlank ( ?individual ) )
    }
}