PREFIX owl: <http://www.w3.org/2002/07/owl#>
CONSTRUCT {
	?ontologyIri a owl:Ontology .
  	?ontologyIri owl:versionIRI ?versionIri .
}
WHERE {
  ?ontologyIri a owl:Ontology .

  OPTIONAL {
   ?ontologyIri owl:versionIRI ?versionIri .
  }
}