PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sgstate: <http://mobi.com/ontologies/shapes-graph/state#>
PREFIX plat: <http://mobi.com/ontologies/platform/config#>

SELECT *
WHERE {
  ?state a plat:State ;
    plat:stateResource/sgstate:record <%RECORDIRI%> .
}