PREFIX mcat: <http://mobi.com/ontologies/catalog#>
PREFIX shapesedit: <http://mobi.com/ontologies/shapes-graph-editor#>

SELECT ?record
WHERE {
	?branch a mcat:Branch .

    ?record a shapesedit:ShapesGraphRecord ;
        mcat:branch ?branch ;
        mcat:masterBranch ?branch .
}