/*-
 * #%L
 * com.mobi.web
 * $Id:$
 * $HeadURL:$
 * %%
 * Copyright (C) 2016 - 2023 iNovex Information Systems, Inc.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */
import {
    Component
} from '@angular/core';

import { OntologyStateService } from '../../../shared/services/ontologyState.service';

/**
 * @class ontology-editor.VisualizationTabComponent
 *
 * A component that creates a page containing an interactive visualization of the ontologies in the imports closure of
 * the currently {@link shared.OntologyStateService#listItem selected ontology}. This component renders a force-directed
 * graph using d3-force layout. The graph is generated by the data retrieved from {@link shared.OntologyStateService}
 * and {@link shared.OntologyManagerService}. The visualization has a limit of 500 nodes. InProgressCommits are not
 * displayed.
 */
@Component({
    templateUrl: './visualizationTab.component.html',
    selector: 'visualization-tab',
    styleUrls: ['./visualizationTab.component.scss']
})
export class VisualizationTabComponent {
    constructor(public os: OntologyStateService){}
}
