PREFIX  muser: <http://mobi.com/ontologies/user/management#>

DELETE {
    GRAPH <http://mobi.com/usermanagement> {
        <http://mobi.com/users/d033e22ae348aeb5660fc2140aec35850c4da997> muser:password ?password .
    }
}
INSERT {
    GRAPH <http://mobi.com/usermanagement> {
        <http://mobi.com/users/d033e22ae348aeb5660fc2140aec35850c4da997> muser:password "{CRYPT}21232F297A57A5A743894A0E4A801FC3{CRYPT}" .
    }
}
WHERE {
    GRAPH <http://mobi.com/usermanagement> {
        <http://mobi.com/users/d033e22ae348aeb5660fc2140aec35850c4da997> muser:password ?password .
    }
}