PREFIX mcat: <http://mobi.com/ontologies/catalog#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?commit ?time
WHERE {
    ?initialCommit (^mcat:baseCommit | ^mcat:auxiliaryCommit)+ ?commit .

    ?commit a mcat:Commit ;
        prov:atTime ?time .
}
ORDER BY ASC(?time)