prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>

select ?type
where {
    graph <http://data.qudt.org/qudt/owl/1.0.0/qudt.owl> {
        ?individual rdf:type owl:NamedIndividual .
        ?individual rdf:type ?type .
        filter (?type != owl:NamedIndividual)
    }
} group by ?type