PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX setting: <http://mobi.com/ontologies/setting#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

CONSTRUCT { ?settingDef ?p ?o .
  ?mainPropertyShape ?mainPropertyShapePred ?mainPropertyShapeObj .
  ?attachedNode ?attachedNodePred ?attachedNodeObj .
  ?attachedProperty ?attachedPropertyPred ?attachedPropertyObj .
}
WHERE {
    ?settingDef a sh:NodeShape ;
        setting:inGroup ?group ;
        rdfs:subClassOf ?settingType ;
        sh:property ?mainPropertyShape ;
        ?p ?o .

    ?mainPropertyShape ?mainPropertyShapePred ?mainPropertyShapeObj .

    OPTIONAL {
        ?mainPropertyShape sh:node ?attachedNode .
        ?attachedNode sh:property ?attachedProperty ;
            ?attachedNodePred ?attachedNodeObj .
        ?attachedProperty ?attachedPropertyPred ?attachedPropertyObj .
    }
}