PREFIX mcat: <http://matonto.org/ontologies/catalog#>

SELECT
    (COUNT(distinct ?record) as ?record_count)
WHERE {
	?record a ?type .
	FILTER(?type IN (mcat:Record, mcat:UnversionedRecord, mcat:VersionedRecord, mcat:VersionedRDFRecord, mcat:OntologyRecord, mcat:MappingRecord, mcat:DatasetRecord))
}