PREFIX dc: <http://purl.org/dc/terms/>
PREFIX matontocat: <http://matonto.org/ontologies/catalog#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT
    (COUNT(distinct ?resource) as ?resource_count)
WHERE {
	?resource a ?type .
	FILTER(?type IN (matontocat:PublishedResource, matontocat:Ontology))
}