PREFIX dc: <http://purl.org/dc/terms/>
PREFIX matontocat: <http://matonto.org/ontologies/catalog#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT
    ?resource
    (GROUP_CONCAT(DISTINCT ?type ; separator = ",") AS ?types)
    ?title
    ?issued
    ?modified
    ?description
    ?identifier
    (GROUP_CONCAT(DISTINCT ?keyword ; separator = ",") AS ?keywords)
    (GROUP_CONCAT(DISTINCT ?distribution ; separator = ",") AS ?distributions)
WHERE {
	?resource a ?type ;
		dc:title ?title ;
		dc:issued ?issued ;
		dc:modified ?modified .

	FILTER(?type IN (matontocat:PublishedResource, matontocat:Ontology, matontocat:Mapping))

    FILTER EXISTS { ?resource a ?type_filter . }

	OPTIONAL { ?resource dc:description ?description } .
	OPTIONAL { ?resource dc:identifier ?identifier } .
    OPTIONAL { ?resource dcat:keyword ?keyword } .
    OPTIONAL { ?resource dcat:distribution ?distribution } .
} GROUP BY ?resource ?title ?issued ?modified ?description ?identifier
