PREFIX mcat: <http://matonto.org/ontologies/catalog#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?commit
WHERE {
    ?commit a mcat:Commit ;
        mcat:onVersionedRDFRecord ?record ;
        prov:wasAssociatedWith ?user .
}