PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX mcat: <http://mobi.com/ontologies/catalog#>
PREFIX policy: <http://mobi.com/ontologies/policy#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX um: <http://mobi.com/ontologies/user/management#>
PREFIX wf: <http://mobi.solutions/ontologies/workflows#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
    %SELECT_VARIABLES%
WHERE {
    VALUES ?iri { %VIEWABLE_RECORDS% }

    ?iri a wf:WorkflowRecord ;
        mcat:catalog ?catalogIri ;
        mcat:masterBranch ?master ;
        dcterm:title ?title ;
        dcterm:issued ?issued ;
        dcterm:modified ?modified ;
        wf:active ?active ;
        wf:workflowIRI ?workflowIRI .
    OPTIONAL {
        ?iri dcterm:description ?description
    }
    OPTIONAL {
        ?iri wf:latestActivity ?executionId .
        ?executionId a wf:WorkflowExecutionActivity ;
            prov:wasAssociatedWith ?executorIri ;
            prov:startedAtTime ?startTime . # XMLSchema#dateTime
        ?executorIri a um:User;
            um:username ?executorUsername .
    
        OPTIONAL {
            ?executorIri foaf:firstName ?executorFirstName .
        }
        OPTIONAL {
            ?executorIri foaf:lastName ?executorLastName .
        }
        # endedAt and succeeded is optional
        OPTIONAL {
            ?executionId wf:succeeded ?succeeded ;
                prov:endedAtTime ?endTime . # XMLSchema#dateTime
        }
    }

    # Generated Fields
    BIND(IF(BOUND(?executorFirstName) && BOUND(?executorLastName), CONCAT(?executorFirstName, " ", ?executorLastName), "") as ?option4)
    BIND(IF(?option4 != "", ?option4, IF(BOUND(?executorFirstName), ?executorFirstName, ?executorUsername)) as ?executorDisplayName)

    BIND(((year(?startTime)-1970)*(31556926)) + (month(?startTime)*(2629743)) +  (day(?startTime)*(86400)) + (hours(?startTime)*3600) + (minutes(?startTime)*60) + seconds(?startTime) as ?startTimeSeconds)
    BIND(((year(?endTime)-1970)*(31556926)) + (month(?endTime)*(2629743)) +  (day(?endTime)*(86400)) + (hours(?endTime)*3600) + (minutes(?endTime)*60) + seconds(?endTime) as ?endTimeSeconds)
    BIND(IF(BOUND(?startTime) && BOUND(?endTime), ?endTimeSeconds - ?startTimeSeconds, 0) as ?runningTime)
    # Status failure|started|success|never_run
    BIND(IF(BOUND(?executionId) && BOUND(?endTime) && BOUND(?succeeded),
      IF(?succeeded = "true"^^xsd:boolean, "success", "failure"),
      "") as ?succeededStatus
    )
    BIND(IF(?succeededStatus != "",
       ?succeededStatus,
       IF(BOUND(?executionId), "started", "never_run")) as ?status
    )
    # FILTERS
    # FILTER - title
    %FILTER_SEARCH%

    # FILTER - startingAfterFilter
    %FILTER_STARTING_AFTER%

    # FILTER - endingBeforeFilter
    %FILTER_ENDING_BEFORE%

    # FILTER - status
    %FILTER_STATUS%
}