PREFIX mcat: <http://mobi.com/ontologies/catalog#>
PREFIX wf: <http://mobi.solutions/ontologies/workflows#>

SELECT ?record
WHERE {
	?record a wf:WorkflowRecord ;
        mcat:catalog ?catalog ;
		wf:workflowIRI ?workflowIRI .
}
