PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wfstate: <http://mobi.solutions/ontologies/workflows/state#>
PREFIX plat: <http://mobi.com/ontologies/platform/config#>

SELECT ?state
WHERE {
  ?state a plat:State ;
     plat:stateResource/wfstate:record <%RECORDIRI%> .
}
