PREFIX catalog: <http://mobi.com/ontologies/catalog#>
PREFIX prov: <http://www.w3.org/ns/prov#>

CONSTRUCT {
  ?deletionSubject ?p ?o
} WHERE {
  {
    SELECT DISTINCT ?deletionSubject WHERE {
      VALUES ?revision { %REVISIONLIST% }
      ?revision catalog:deletions ?deletionsGraph .
      GRAPH ?deletionsGraph {
        ?deletionSubject ?p ?o .
      }
    }
  }

  VALUES ?revision { %THISREVISION% }
  ?revision catalog:additions ?additionsGraph .
  GRAPH ?additionsGraph {
    ?deletionSubject ?p ?o .
  }
}
