PREFIX mcat: <http://mobi.com/ontologies/catalog#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?parent
WHERE {
    ?commit a mcat:Commit ;
        (mcat:baseCommit | mcat:auxiliaryCommit)+ ?parent;
        prov:generated ?revision.

    ?parent prov:atTime ?time .

    ?revision a mcat:Revision ;
        mcat:additions ?additions;
        mcat:deletions ?deletions .

    FILTER (exists {
        SELECT ?additions {
            ?entity ?p ?o .
        }
    } || exists {
        SELECT ?deletions {
            ?entity ?p ?o .
        }
    })
}
ORDER BY DESC(?time)