PREFIX catalog: <http://mobi.com/ontologies/catalog#>
PREFIX prov: <http://www.w3.org/ns/prov#>

CONSTRUCT {
  ?s ?p ?o
} WHERE {
  VALUES ?commit { %COMMITLIST% }

  GRAPH ?commit {
      ?commit prov:generated ?revision .
      ?revision catalog:additions ?additionsGraph .
  }

  GRAPH ?additionsGraph {
    ?s ?p ?o .
  }
}
