PREFIX catalog: <http://mobi.com/ontologies/catalog#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?s ?p ?o WHERE {
  VALUES ?commit { %COMMITLIST% }
  VALUES ?s { %SUBJECTLIST% }

  GRAPH ?commit {
    ?commit prov:generated ?revision .
    ?revision catalog:additions ?additionsGraph .
  }
  GRAPH ?additionsGraph {
    ?s ?p ?o .
  }
}