PREFIX dc: <http://purl.org/dc/terms/>
PREFIX mcat: <http://mobi.com/ontologies/catalog#>

SELECT
    ?distribution
WHERE {
	?resource a ?type ;
	    mcat:distribution ?distribution .

	FILTER(?type IN (mcat:UnversionedRecord, mcat:Version, mcat:Tag))
}