PREFIX catalog: <http://mobi.com/ontologies/catalog#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?s
WHERE {
  VALUES ?commit { %COMMITLIST% }

  GRAPH ?commit {
      ?commit prov:generated ?revision .
      ?revision catalog:deletions ?deletionsGraph .
  }
  GRAPH ?deletionsGraph {
    ?s ?p ?o .
  }
}