prefix mq: <http://mobi.com/ontologies/merge-requests#>

select ?parent (group_concat(?child) as ?chain)
where {
    ?parent a mq:Comment ;
          mq:onMergeRequest ?mergeRequest ;
          mq:replyComment+ ?child .

    FILTER NOT EXISTS {
        ?comment mq:replyComment ?parent .
    }
}
GROUP BY ?parent